packages:
  - "packages/*"
  - "packages/@bds/*"
  - "packages/fe/*"
  - "packages/fe/@bds/*"

catalog:


catalogs:
  common:
    "cross-env": "^7.0.3"
    "lodash": "^4.17.21"
    "vite": "^6.3.5"
    "vitest": "^3.1.3"
    "tslib": "^2.8.1"
    "esbuild": "^0.25.4"
    "tsconfig-paths": "^4.2.0"
    "@biomejs/biome": "^1.9.4"
    "prettier": "^3.5.3"
    "turbo": "^2.5.3"
    "@eslint/js": "^9.26.0"
    "@next/eslint-plugin-next": "^15.3.0"
    "sass": "^1.88.0"
    "eslint": "^9.26.0"
    "eslint-config-prettier": "^10.1.1"
    "eslint-plugin-only-warn": "^1.1.0"
    "eslint-plugin-react": "^7.37.4"
    "eslint-plugin-react-hooks": "^5.2.0"
    "eslint-plugin-turbo": "^2.5.0"
    "eslint-plugin-react-refresh": "^0.4.19"
    "globals": "^16.1.0"
    "typescript": "^5.8.2"
    "typescript-eslint": "^8.32.0"
    "@types/jest": "^29.5.14"
    "@types/node": "^22.15.18"
    "@types/supertest": "^6.0.3"
    "jest": "^29.7.0"
    "jest-environment-jsdom": "^29.7.0"
    "jest-expect-message": "^1.1.3"
    "jest-junit": "^16.0.0"
    "jest-mock": "^29.7.0"
    "jest-mock-extended": "4.0.0-beta1"
    "rimraf": "^6.0.1"
    "supertest": "^7.1.1"
    "ts-jest": "^29.3.3"
    "tsc-alias": "^1.8.16"
    "tsc-watch": "^6.2.1"
    "@testing-library/jest-dom": "^6.6.3"
    "@testing-library/user-event": "^14.6.1"
    "sass-embedded": "^1.88.0"
    "vite-plugin-svgr": "^4.3.0"
    "vitest-mock-extended": "^3.1.0"
    
  frontend:
    "react": "^19.1.0"
    "react-dom": "^19.1.0"
    "@types/react": "^19.1.2"
    "@types/react-dom": "^19.1.2"
    "@vitejs/plugin-react": "^4.4.1"
    "@vitejs/plugin-legacy": "^6.1.1"
    "browserslist": "^4.24.5"
    "browserslist-to-esbuild": "^2.1.1"
    "unplugin-icons": "^22.1.0"
    "unplugin-react-components": "^0.1.4"
    "vite-plugin-static-copy": "^3.0.0"
    